### PR TITLE
Pull ImGui master 1.84.1 and generate

### PR DESCRIPTION
**Pull request by lmariscal**
Update submodule ImGui to tag v1.84.1 and generate bindings.
Created another commit with v1.83 and v1.84 for historic reasons. Also took the liberty to update the README.md
If I am missing something please let me know.

### CODE REVIEW

**Comment by wobes1** [comment]
Hey @lmariscal thank you for the pull request! Would you be able to generate docking branch as well? 
I would do it myself but I was not able to generate bindings myself, I am only able to generate backend bindings, is there a special way to generate full bindings for imgui?

Thanks!

**Comment by lmariscal** [comment]
I screwed up a push on my side, but fixed it via a hard reset haha.
@wobes1 pushed the latest `docking` branch to the `docking_inter` branch https://github.com/lmariscal/cimgui/tree/docking_inter

All the tools needed to generate full bindings are located in the `generator` directory. You need to have luajit installed and a compiler. All you need to do is run `./generator.sh` or `./generator.bat`.
The hard part would be when some changes happen that break the generator, in that case it would be about entering and fixing the lua generator, but in the small number of tests I have run it seems these past versions haven't need it.

**Comment by wobes1** [comment]
@lmariscal thank you for your reply! I do have luajit installed but every time I ran generator script my output is this. but never the actual c header and implementation

image

**Comment by lmariscal** [comment]
@wobes1 my output folder is the same, the generated `cimgui.cpp`, `cimgui.h` ends up being copied in the parent directory.

```lua
-------------------copy C files to repo root
copyfile("./output/cimgui.h", "../cimgui.h")
copyfile("./output/cimgui.cpp", "../cimgui.cpp")
os.remove("./output/cimgui.h")
os.remove("./output/cimgui.cpp")
print"all done!!"
```

Copies the files in the output folder and removes them.

**Comment by wobes1** [comment]
Oh my god, how I did not see that. Thank you so much @lmariscal

**Comment by sonoro1234** [comment]
@lmariscal Thank you for this.
I just did the updates to master and docking_inter branches

**Pull request closed without merging**
