### PR TITLE
CMake remake

### PR DESCRIPTION
**Pull request by gaurapanasenko**
Now it is easy to pack library with cpack and use library with:
```cmake
find_package(cimgui REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE ${CIMGUI_LIBRARIES})
```

### CODE REVIEW

**Comment by sonoro1234** [comment]
compilation with Freetype gets broken for me, not only for missing `PATHS ${FREETYPE_PATH}` (I installed freetype to standard path but freetype is not found)

If I add `PATHS ${FREETYPE_PATH}` the error is
```
C:\LuaGL\gitsources\anima\LuaJIT-ImGui\cimgui\imgui\misc\freetype\imgui_freetype.cpp:35:10: fatal error: ft2build.h: No such file or directory
 #include <ft2build.h>
          ^~~~~~~~~~~~
```

**Comment by sonoro1234** [comment]
For being backward compatible this should be used

```
if (EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/../imgui/backends)
	set(BAKENDS_FOLDER "../imgui/backends/")
else()
	set(BAKENDS_FOLDER "../imgui/examples/")
endif()
```

As found in https://github.com/cimgui/cimgui/blob/master/backend_test/CMakeLists.txt

**Comment by gaurapanasenko** [comment]
> compilation with Freetype gets broken for me, not only for missing `PATHS ${FREETYPE_PATH}` (I installed freetype to standard path but freetype is not found unless I use `find_package(freetype REQUIRED PATHS ${CMAKE_PREFIX_PATH})`)
> 
> If I add `PATHS ${FREETYPE_PATH}` the error is
> 
> ```
> C:\LuaGL\gitsources\anima\LuaJIT-ImGui\cimgui\imgui\misc\freetype\imgui_freetype.cpp:35:10: fatal error: ft2build.h: No such file or directory
>  #include <ft2build.h>
>           ^~~~~~~~~~~~
> ```
> 
> It is only solved by `list(APPEND IMGUI_LIBRARIES freetype)`

You got compile error when including header file. This is why I added:
```cmake
```

**Comment by gaurapanasenko** [comment]
> If I add `PATHS ${FREETYPE_PATH}` the error is
> 
> ```
> C:\LuaGL\gitsources\anima\LuaJIT-ImGui\cimgui\imgui\misc\freetype\imgui_freetype.cpp:35:10: fatal error: ft2build.h: No such file or directory
>  #include <ft2build.h>
>           ^~~~~~~~~~~~
> ```

You got compile error when including header file. This is why I added:
```cmake
list(APPEND IMGUI_INCLUDE_DIRS ${FREETYPE_INCLUDE_DIRS})
```

Did you copied header files to ${CMAKE_PREFIX_PATH} when you was installing Freetype?

**Comment by sonoro1234** [comment]
> You got compile error when including header file. This is why I added:
> 
> ```cmake
> list(APPEND IMGUI_INCLUDE_DIRS ${FREETYPE_INCLUDE_DIRS})
> ```

Not working for me



> Did you copied header files to ${CMAKE_PREFIX_PATH} when you was installing Freetype?

Yes. I did the cmake installation as explained in CMakeLists.txt from freetype:

first: `cmake -G"MinGW Makefiles" -B build -D BUILD_SHARED_LIBS=true -D CMAKE_BUILD_TYPE=Release ../../freetype2`
second:`cmake --build build --target install`

**Comment by gaurapanasenko** [comment]
@sonoro1234 I got exactly same compile error when tried to add PATHS in find_package. I tried also `${CMAKE_SYSTEM_PREFIX_PATH}`. So for now I appended `FREETYPE_PATH` to `CMAKE_SYSTEM_PREFIX_PATH` because [cmake documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_PREFIX_PATH.html) says that this variable is used by find_package but not sure that it will work for you.
What environment you use for compilation? I use OpenSUSE Tumbleweed and tried prebuild freetype package and custom build freetype package with cpack and all works good. Later I can try to compile and pack it on Windows with MSYS2.

**Comment by sonoro1234** [comment]
I have been using https://github.com/freetype/freetype2.git with mingw-w64 without MSYS.
I seems outdated so I used https://gitlab.freedesktop.org/freetype/freetype but it fails to run cmake

**Review by lastthyme — APPROVED** [review]

**Pull request closed without merging**
