### PR TITLE
Create a branch tracking the upstreaming docking branch

### PR DESCRIPTION
**Pull request by rasky**
In preparation for the upcoming upstream docking/viewport branch merge, I think it would be very useful if the ecosystem of bindings could begin implementing support for it, since its a large change that has multiple effects also on backends (especially the multi viewport support).

This means that, in turn, it would be great if cimgui could publish itself a `docking` branch, tracking the upstream one, as that would make so much easier for other language bindings to follow. This PR implements support for it, to the best of my understanding. I didn't test it much at this point, but I managed to recompile a non-trivial application with it and it seems to work. Anyway, I think it's a first step.

### CODE REVIEW

**Comment by sonoro1234** [comment]
It should not be merged on máster branch.
Why not viewport branch instead of docking?
Was the generation done without any issues?

**Comment by rasky** [comment]
> It should not be merged on máster branch but on docking branch instead.

Yes, my PR is meant to be merged on a new branch. I can’t do that from the Github UI, until you create a branch on this repo; then I can redo the PR on it.

> Why not viewport branch instead of docking?

Viewport branch doesn’t exist anymore, now it’s part of the docking branch.

> Was the generation done without any issues?

Yes.

> If so, why is commit needed?

Because it lowers the barrier to adapt other bindings. For instance, after you merge this into a new branch, I can open a new PR on the rust bindings, which import cimgui as sub module; I can make the submodule track the docking branch here, and adapt the Rust bindings to export the new APIs (non-trivial); and after *that* is done, I have PRs for the rust-imgui-OpenGL backend, which in turn will have to point to a “docking” branch in Rust’s bindings, plus non-trivial additions in the code to support viewports.  If we then update the branch here every month, the new features and bug fixes are easy to import.

If you don’t commit this, the rust bindings has no simple way of using the docking branch. I would have to talk the Rust maintainer to implement a docking branch that imports a forked version of cimgui that I would have to maintain elsewhere, and the Rust maintainer could easily object that basing work on a non-official fork of cimgui can mean wasting time. I would think the same, if I were the maintainer.

I hate long-lived branches with a passion, but that’s where we are. Docking branch is big and has many changes, the sooner we start supporting in non-C++ languages, the sooner we can benefit from it once it’s merged. 

I understand that for cimgui there’s almost nothing to do, but in other languages’ back ends there’s lot of code to write, and this PR has no cost for you and helps downstream a lot. I can send regular updates via PRs to track upstream, and I can take care of maintaining it and raising issues I meet with you, if ever: those are all things that might end up on your plate anyway after it’s merged.

**Comment by sonoro1234** [comment]
After reading your arguments I have created docking branch generated from imgui 1.74 docking, as I wasn't able to take your PR into cimgui/docking.
Thanks!!

**Comment by rasky** [comment]
Thanks!

**Comment by sonoro1234** [comment]
> I understand that for cimgui there’s almost nothing to do, but in other languages’ back ends there’s lot of code to write

In the case of my LuaJIT-ImGui binding I have only had to chang flags before init
https://github.com/sonoro1234/LuaJIT-ImGui/blob/docking/examples/minimal_main_viewport.lua

```lua
local igio = ig.GetIO()
igio.ConfigFlags = ig.lib.ImGuiConfigFlags_ViewportsEnable + igio.ConfigFlags
igio.ConfigFlags = ig.lib.ImGuiConfigFlags_DockingEnable + igio.ConfigFlags
```
and rendering loop change after ig.Render:

```lua
    if bit.band(igio.ConfigFlags , ig.lib.ImGuiConfigFlags_ViewportsEnable) ~= 0 then
        ig.UpdatePlatformWindows();
        ig.RenderPlatformWindowsDefault();
    end
```

>  I can send regular updates via PRs to track upstream

Yes, in case I forget to update this branch, please make updating PR against docking branch.

**Pull request closed without merging**
