### PR TITLE
Sh generator: pass cmdline args

### PR DESCRIPTION
**Pull request by gucio321**
ref #212

### CODE REVIEW

**Comment by gucio321** [comment]
let me explain a bit:
with current implementation it is not possible to request e.g. "comments" generation without editing `generator.sh`.
now, I can specify:
`./generator.sh --target "comments"`

**Comment by sonoro1234** [comment]
What will be needed when 'nochar' is desired but not 'noimstrv'?
Or to skip internal generation?

**Comment by gucio321** [comment]
good point, thank you.
Now they're set by default, so you by specifying any options, you overwrite defaults

**Comment by sonoro1234** [comment]
No, new options would just be added to defaults: internal and noimstrv

**Comment by sonoro1234** [comment]
Ohh, I see. I guess `./generator.sh -t " "` would override internal also.
Thanks

**Comment by sonoro1234** [comment]
If the same could be done in generator.bat it would be perfect.

**Comment by gucio321** [comment]
> If the same could be done in generator.bat it would be perfect.

ugh, I know, however I'm not familiar with windows scripting at all :cry: I can ask GPT

**Comment by gucio321** [comment]
@sonoro1234  they says something like this:
```bat
@echo off

REM This script must be executed in this directory
REM All the output goes to generator/output folder
REM .cpp and .h files:
REM cimgui.h and cimgui.cpp with gcc preprocess
REM cimgui_nopreprocess.h and cimgui_nopreprocess.cpp generated without preprocess
REM cimgui_impl.h with implementation function cdefs
REM lua and json files:
REM definitions.lua for function definitions
REM structs_and_enums.lua with struct and enum information-definitions
REM impl_definitions.lua for implementation function definitions

REM Process files
REM arg[1] compiler name gcc, clang, or cl
REM arg[2] options as words in one string: internal for imgui_internal generation, freetype for freetype generation, comments for comments generation, nochar to skip char* function version, noimstrv to skip imstrv
REM examples: "" "internal" "internal freetype" "comments internal"
REM arg[3..n] name of implementations to generate and/or CLFLAGS (e.g. -DIMGUI_USER_CONFIG or -DIMGUI_USE_WCHAR32)

REM Parse command line arguments
set TARGETS=internal noimstrv
set CFLAGS=glfw opengl3 opengl2 sdl2

:help
echo Usage of generator.bat:
echo   -t --target    specify which imgui features should be generated
echo                 (default: %TARGETS%)
echo   -c --cflags    specify additional gcc flags
echo                 (default: %CFLAGS%)
echo   -h --help      show this message and exit
goto :eof

:parse_args
if "%1" == "-c" goto cflags
if "%1" == "--cflags" goto cflags
if "%1" == "-t" goto targets
if "%1" == "--target" goto targets
if "%1" == "-h" goto help
if "%1" == "--help" goto help
goto positional_args

:cflags
set CFLAGS=%2
shift
shift
goto parse_args

:targets
set TARGETS=%2
shift
shift
goto parse_args

:positional_args
if "%OSTYPE%" == "cygwin" goto set_suffix
if "%OSTYPE%" == "msys" goto set_suffix
if "%OSTYPE%" == "win32" goto set_suffix

:execute
luajit%suffix% ./generator.lua gcc "%TARGETS%" %CFLAGS%
goto :eof

:set_suffix
set suffix=.exe
goto execute
```
But can't say if it will work...

**Comment by sonoro1234** [comment]
Thankyou, I will test it.

**Pull request merged**
