### PR TITLE
Update CMake to a modern module system and create simple test

### PR DESCRIPTION
**Pull request by lmariscal**
Hi, creating a pull request for a modern cmake module system, together with a basic cimgui test based on the imgui [null example](https://github.com/ocornut/imgui/blob/master/examples/example_null/main.cpp).

This test is also represented as a travis.yml file which uses this cmake files to link the cimgui library to the test executable.

Please let me know your thoughts and if the changes were too pompous.

Edit: Current travis build status for the fork repo: https://travis-ci.org/lmariscal/cimgui

### CODE REVIEW

**Comment by sonoro1234** [comment]
Travis can be enable for windows also?

**Comment by lmariscal** [comment]
Travis appears to have added Windows since October of 2018: https://blog.travis-ci.com/2018-10-11-windows-early-release

And yes, I tried to keep CMake at the lowest version possible, if this conflicts with the project I can remove it from the PR but I do find it useful at the creation of other CMake projects and easy linkage.

I will add windows support for the CI.

**Comment by lmariscal** [comment]
Windows has been added to the travis CI file.
Again you can see the build at: https://travis-ci.org/lmariscal/cimgui/builds/566462966

Please let me know your thoughts.

**Comment by sonoro1234** [comment]
There should be an account for http://travis-ci.org/cimgui/cimgui?

**Comment by Extrawurst** [comment]
@sonoro1234 does it work now? I just got an email saying that travis-ci is registered now, right?

**Comment by sonoro1234** [comment]
Yes, it worked with my github password. Thank you

**Comment by sonoro1234** [comment]
lets try it!!!

**Comment by sonoro1234** [comment]
@lmariscal  Could you please post for future reference which are the characteristic used from CMake 3.10?

**Comment by lmariscal** [comment]
Sure,
```
target_link_libraries
target_compile_definitions
target_include_directories
```
Are some available since 2.8.11 and other specific behavior since 3.0 mostly related at how modules link together.

The "culprit" would be `C_STANDARD` that was implemented in 3.1.

**Pull request merged**
