### PR TITLE
Simplify CMake invocation in CI

### PR DESCRIPTION
**Pull request by oprypin**

### CODE REVIEW

**Comment by sonoro1234** [comment]
I am not able to review this PR. perhaps @lmariscal ?

**Comment by lmariscal** [comment]
I think it is okay, it removes certain lines which have become obsolete since Travis has improved some defaults.
I only have one question @oprypin: Why bionic and not focal?

https://docs.travis-ci.com/user/reference/focal/ <- Changes that the focal (Ubuntu 20.04 LTS) has.

**Comment by sonoro1234** [comment]
Thanks to both!!

**Comment by sonoro1234** [comment]
Now I am facing the problem of not being able to apply this to docking_inter branch.
I would appreciate some help on this!!

**Pull request merged**
