### PR TITLE
Compile without exception support to link without stdc++

### PR DESCRIPTION
**Pull request by s-ol**

### CODE REVIEW

**Comment by s-ol** [comment]
1.) imgui doesn't use exceptions, see ocornut/imgui#504. Since I am using cimgui and want to embed into a non-C++ codebase, I would prefer not to link to libc++ (potentially even not to link against libc).2
2.) How would a user benefit from exceptions when they are embedding ImGUI via the C ABI? C doesn't have exceptions and if the user was embedding in C++ they should just embed ImGUI directly

**Comment by sonoro1234** [comment]
> if the user was embedding in C++ they should just embed ImGUI directly

May be the user wants exceptions but is performing an ffi binding (which cant be done with C++ interface)

**Comment by s-ol** [comment]
@sonoro1234 but which kind of bindings? The hosting application/code can still be compiled with exceptions.

Please correct me If I'm wrong, but if ImGUI does not throw exceptions, and it is compiled into a `.so` that only exports C-ABI bindings (which is not supporting exceptions), then what is the purpose of having (unused) exception handling capabilities linked into that binary?

**Comment by sonoro1234** [comment]
> The hosting application/code can still be compiled with exceptions.

This would be ideal if could be included in this PR: Provide a mechanism by which exceptions or not is configurable.

**Comment by s-ol** [comment]
I was talking about the **hosting application**, which is compiled independently of the cimgui library. The user can configure their build system with or without exception support.

**Pull request merged**
