### PR TITLE
Makefile: add option to compile as static lib

### PR DESCRIPTION
**Pull request by slmjkdbtl**

### CODE REVIEW

**Comment by sonoro1234** [comment]
Not using makefiles but cmake I am not able to review. Perhaps somebody could chime in?

Notice: There was a previous PR for doing that with cmake

**Comment by slmjkdbtl** [comment]
Hi! It works well on my local machine (macOS 10.14.6) and should work on all Linux too, but will appreciate a test / review.

I'm aware of the CMake PR but want to add a Make version because it might be more accessible for some people?

**Comment by sonoro1234** [comment]
As nobody complains you could be the only Makefile user so lets merge as it is ok for you.

**Comment by s-ol** [comment]
I didn't have a chance to test it, but it looks right and I would definitely use a simpler build system :+1:

**Comment by sonoro1234** [comment]
>  I would definitely use a simpler build system

Which one would be simpler?

**Comment by s-ol** [comment]
@sonoro1234 CMake outputs Makefiles, so I would say Makefiles are simpler :wink:

**Pull request merged**
