### PR TITLE
Internal funcs

### PR DESCRIPTION
**Pull request by sonoro1234**
Merge internal function generation into master

### CODE REVIEW

**Comment by ocornut** [comment]
Hello,

Could we make those optional, with e.g. a `#define CIMGUI_INTERNALS` define to hide them otherwise? This would double as making it clearer in the header file that they are internal functions.
At least for functions, then ideally also for the defines.

Cheers.
Omar

**Comment by sonoro1234** [comment]
They are already optional in two ways:

In generator.bat (sh): https://github.com/cimgui/cimgui/blob/master/generator/generator.bat#L18

By the location field in https://github.com/cimgui/cimgui#definitions-description that allow binding makers to skipt those from internal location.

**Comment by ocornut** [comment]
But most people don't run the generator themselves and a same codebase can want to use internals for e.g. custom widgets but not everywhere, but it feels like the generated bindings could selectively hide it behind a define (or better have it in cimgui_internal.h instead).

**Comment by sonoro1234** [comment]
> a same codebase can want to use internals for e.g. custom widgets but not everywhere

In this case they need cimgui to wrap internals and also to compile internal wrappings in order to use them.
But in order to hide them to the final binding user just dont expose them if the location field in json is `imgui_internal`

**Comment by ocornut** [comment]
I am saying two things:

- In same codebase we want users to be able to "see" internals from SOME source files, but not from all their source files.
- In the header file we want users to be able to distinguish internals from public.

So a same copy of cimgui should allow using internals while making that distinction.

The current output prevents those two uses.

**Comment by sonoro1234** [comment]
>     * In the header file we want users to be able to distinguish internals from public.

In cimgui.h all internal functions are after public ones, we could print a comment before begining of internal function for example



>     * In same codebase we want users to be able to "see" internals from SOME source files, but not from all their source files.

I am not sure to understand

**Comment by ocornut** [comment]
> In cimgui.h all internal functions are after public ones, we could print a comment before begining of internal function for example

Yes, that would work, but it also need to be done for internal enums/flags. Having everything is a separate file is simpler.

> I am not sure to understand

People want to restrict use of internal to specific source files (e.g. this_project_custom_widgets.cpp) and not every files of the project using imgui. Having everything in a separate file would allow this and mimic how dear imgui works.

**Pull request merged**
