### PR TITLE
Use consistent JSON type for empty tables

### PR DESCRIPTION
**Pull request by tversteeg**
Similar to PR #154, but for JSON keys. This will ensure that empty JSON dictionaries will be properly set using `{}` and empty JSON arrays with `[]`.

### CODE REVIEW

**Comment by sonoro1234** [comment]
Perhaps I would prefer setting (also in Lua) empty defaults to nil

**Comment by tversteeg** [comment]
That also works for me, do you want me to change this PR so empty tables are `nil`?

**Comment by oprypin** [comment]
It shouldn't be nil conceptually. There's no such thing as a "defaultless function". A function with 0 defaults should be a list of 0 length.

In the current state this change would allow me to remove this workaround: https://github.com/oprypin/crystal-imgui/blob/1a0cc4237191dae7eaeb36ed88ec7563873a7492/generate.cr#L245-L249

Changing it to nil would merely require a different workaround.

Anyway, while I fully agree with the outcome of this change, the implementation doesn't look amazing :\

**Comment by tversteeg** [comment]
I also feel like this implementation isn't that great, I struggled to find a proper place for this change in the current structure. I would happily move it to somewhere else if that would make it a bit less ugly.

**Comment by sonoro1234** [comment]
To make the solution less "ad hoc" just pushed a commit giving an option to json.encode `dict_on_empty`

Thanks for pointing issue!!

**Comment by tversteeg** [comment]
Thank you for implementing it, your solution is a lot cleaner!

**Pull request closed without merging**
